In [3]:
#Building a neural network of a single layer
import numpy as np
from numpy import exp,array,random,dot

In [22]:
class NeuralNetwork():
    def __init__(self):
        #seeding the random number generator
        random.seed(1)
        #modelling a single neuron with 3 inputs and 1 output, assign random weights
        #in range -1 to 1 to a 3 X 1 matrixand mean 0
        self.synaptic_weights = 2*random.random((3,1)) - 1
    #defining the activation function, weighted sum of inputs is 
    #passed through it and it gets normalised b/w 0 and 1
    def __sigmoid(self,x):
        return (1/(1 + exp(-x)))
    def predict(self,inputs):
        #pass inputs through the neural network(single neuron)
        return self.__sigmoid(dot(inputs,self.synaptic_weights))
    #gradient of sigmoid curve
    def __sigmoid_derivative(self,x):
        return x * (1-x)
    def train(self,inputs,ioutputs,iterations):
        for iteration in xrange(iterations):
            output = self.predict(inputs)
            #calculate error
            error = ioutputs - output
            #multiplying the error by input and gradient of the sigmoid curve
            #less confident weights are adjusted more
            adjustment = dot(inputs.T, error*self.__sigmoid_derivative(output))
            #adjust the weights
            self.synaptic_weights += adjustment

In [23]:
#initialise a single neuron neural network
nn = NeuralNetwork()
print("Synaptic Weights are:")
print nn.synaptic_weights
#defining the training set with 3 input and 1 output value
x_train = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
y_train = array([[0,1,1,0]]).T
#train the neural network using the training set, we can do it for a number
#of iterations
nn.train(x_train,y_train,10000)
print("New Synaptic Weights after training:")
print nn.synaptic_weights
print("Output for [0,0,1] is:")
nn.predict(array([0,0,1]))

Synaptic Weights are:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New Synaptic Weights after training:
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Output for [0,0,1] is:


array([ 0.009664])

In [36]:
#expanding the neural network for more number of layers
class NeuralNetwork():
    def __init__(self):
        #seeding the random number generator
        random.seed(1)
        #Defining the number of nodes in subsequent layers
        l2 = 5
        l3 = 7
        l4 = 8
        l5 = 4
        # assign random weights to matrices in network
        # format is (no. of nodes in previous layer) x (no. of nodes in following layer)
        self.synaptic_weights1 = 2 * random.random((3, l2)) -1
        self.synaptic_weights2 = 2 * random.random((l2, l3)) -1
        self.synaptic_weights3 = 2 * random.random((l3, l4)) -1
        self.synaptic_weights4 = 2 * random.random((l4, l5)) -1
        self.synaptic_weights5 = 2 * random.random((l5, 1)) -1
    #defining the activation function, weighted sum of inputs is 
    #passed through it and it gets normalised b/w 0 and 1
    def __sigmoid(self,x):
        return (1/(1 + exp(-x)))
    #gradient of sigmoid curve
    def __sigmoid_derivative(self,x):
        return x * (1-x)
    #passing the inputs through the different layers of the neural network
    def predict(self,inputs):
        f2 = self.__sigmoid(dot(inputs, self.synaptic_weights1))
        f3 = self.__sigmoid(dot(f2, self.synaptic_weights2))
        f4 = self.__sigmoid(dot(f3, self.synaptic_weights3))
        f5 = self.__sigmoid(dot(f4, self.synaptic_weights4))
        output = self.__sigmoid(dot(f5, self.synaptic_weights5))
        return output
    def train(self,inputs,ioutputs,iterations):
        for iteration in xrange(iterations):
            #passing the training set through the neural network 
            #through the successive layers
            f2 = self.__sigmoid(dot(inputs, self.synaptic_weights1))
            f3 = self.__sigmoid(dot(f2, self.synaptic_weights2))
            f4 = self.__sigmoid(dot(f3, self.synaptic_weights3))
            f5 = self.__sigmoid(dot(f4, self.synaptic_weights4))
            output = self.__sigmoid(dot(f5, self.synaptic_weights5))
            #error calculation and backpropagation
            del6 = (ioutputs - output)*self.__sigmoid_derivative(output)
            del5 = dot(self.synaptic_weights5, del6.T)*(self.__sigmoid_derivative(f5).T)
            del4 = dot(self.synaptic_weights4, del5.T)*(self.__sigmoid_derivative(f4).T)
            del3 = dot(self.synaptic_weights3, del4)*(self.__sigmoid_derivative(f3).T)
            del2 = dot(self.synaptic_weights2, del3)*(self.__sigmoid_derivative(f2).T)
            #calculation of the adjustments of each layer
            adjustment5 = dot(f5.T, del6)
            adjustment4 = dot(f4.T, del5.T)
            adjustment3 = dot(f3.T, del4.T)
            adjustment2 = dot(f2.T, del3.T)
            adjustment1 = dot(inputs.T, del2.T)
            #adjusting the weights
            self.synaptic_weights1 += adjustment1
            self.synaptic_weights2 += adjustment2
            self.synaptic_weights3 += adjustment3
            self.synaptic_weights4 += adjustment4
            self.synaptic_weights5 += adjustment5

In [37]:
#initialise a single neuron neural network
nn = NeuralNetwork()
print("Synaptic Weights of layer 1 are:")
print nn.synaptic_weights1
print("Synaptic Weights of layer 2 are:")
print nn.synaptic_weights2
print("Synaptic Weights of layer 3 are:")
print nn.synaptic_weights3
print("Synaptic Weights of layer 4 are:")
print nn.synaptic_weights4
print("Synaptic Weights of layer 5 are:")
print nn.synaptic_weights5
#defining the training set with 3 input and 1 output value
x_train = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
y_train = array([[0,1,1,0]]).T
nn.train(training_set_inputs, training_set_outputs, 2000)
print("New Synaptic Weights of layer 1 are:")
print nn.synaptic_weights1
print("New Synaptic Weights of layer 2 are:")
print nn.synaptic_weights2
print("New Synaptic Weights of layer 3 are:")
print nn.synaptic_weights3
print("New Synaptic Weights of layer 4 are:")
print nn.synaptic_weights4
print("New Synaptic Weights of layer 5 are:")
print nn.synaptic_weights5
print("Output for [0,0,1] is:")
nn.predict(array([0,0,1]))

Synaptic Weights of layer 1 are:
[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]]
Synaptic Weights of layer 2 are:
[[ 0.34093502 -0.1653904   0.11737966 -0.71922612 -0.60379702  0.60148914
   0.93652315]
 [-0.37315164  0.38464523  0.7527783   0.78921333 -0.82991158 -0.92189043
  -0.66033916]
 [ 0.75628501 -0.80330633 -0.15778475  0.91577906  0.06633057  0.38375423
  -0.36896874]
 [ 0.37300186  0.66925134 -0.96342345  0.50028863  0.97772218  0.49633131
  -0.43911202]
 [ 0.57855866 -0.79354799 -0.10421295  0.81719101 -0.4127717  -0.42444932
  -0.73994286]]
Synaptic Weights of layer 3 are:
[[-0.96126608  0.35767107 -0.57674377 -0.46890668 -0.01685368 -0.89327491
   0.14823521 -0.70654285]
 [ 0.17861107  0.39951672 -0.79533114 -0.17188802  0.38880032 -0.17164146
  -0.90009308  0.07179281]
 [ 0.32758929  0.02977822  0.88918951  0.17311008  0.80680383 -

array([ 0.37772035])